quartz_feb2010: new verb
Winetricks/winetricks pull request #1636
Opened 2020-10-20 13:35 UTC by kakurasan

RPG Maker (RPG Tkool) XP/VX/VXAce games need `gmdls`, `dmsynth`, `dmusic`, `dmband`, `dmime`, `dmstyle`, `dsdmo` and `dsound` for MIDI playback, but after installing them MP3 playback needs the "Feb 2010" version of `quartz`: Built-in version doesn't play MP3 files properly with native `dsound`, and "[win7sp1](https://github.com/Winetricks/winetricks/commit/20ec914d2025d0d3aec3c33cc75a276d53336db9)" version doesn't work.

So I really need the "Feb 2010" version of `quartz` for RPG Maker games.

2020-10-20 13:57 UTC, gverm requested changes
Change the override to `w_override_dlls native,builtin quartz` and move it above `w_try_regsvr quartz.dll`.

2020-10-20 15:34 UTC, zfigura commented
What's broken with all builtin components? Is there a bug for this?

2020-10-20 15:35 UTC, zfigura commented
Never mind, I can read now.

2020-10-21 13:24 UTC, kakurasan commented
@zfigura
When built-in `dsound` is used, MP3 playback is working as of Wine 5.19 (but MIDI playback is not working).

When native `dsound` (needed for MIDI playback) is used, I can hear nothing or only the first < 1 second of the MP3 file:
```
...
0154:fixme:quartz:DSoundRender_UpdatePositions Underrun of data occurred!
0154:fixme:quartz:DSoundRender_SendSampleData Sample dropped 22372 of 4608 bytes
014c:fixme:quartz:DSoundRender_SendSampleData Sample dropped 17940 of 4608 bytes
0150:fixme:quartz:DSoundRender_SendSampleData Sample dropped 13332 of 4608 bytes
0154:fixme:quartz:DSoundRender_SendSampleData Sample dropped 8724 of 4608 bytes
014c:fixme:quartz:DSoundRender_SendSampleData Sample dropped 4292 of 4608 bytes
014c:fixme:quartz:DSoundRender_UpdatePositions Underrun of data occurred!
014c:fixme:quartz:DSoundRender_SendSampleData Sample dropped 5792 of 4608 bytes
014c:fixme:quartz:DSoundRender_SendSampleData Sample dropped 1360 of 4608 bytes
014c:fixme:quartz:DSoundRender_UpdatePositions Underrun of data occurred!
...
```
Since you already tested `sound_tester.exe` (See https://bugs.winehq.org/show_bug.cgi?id=48315#c3) last December, you can confirm the issue with it.

2020-10-23 07:45 UTC, austin987 commented
@zfigura/@gverm, given that you've both deal with quartz/etc. upstream, are you okay with the change?

2020-10-23 15:36 UTC, zfigura commented
Yeah, it makes sense to me.

2020-10-23 15:42 UTC, gverm commented
Same here.

2020-10-24 08:31 UTC, merged