Fix problem with symlinked dlls and fix wmp11 package.
Winetricks/winetricks pull request #1847
Opened 2021-11-16 09:37 UTC by patlefort

This PR fix some problems when a wine prefix contain symlinked dlls in its system32 or syswow64 folders.

* Add `w_try_cp_dll` function. This function will detect and remove symlinks before copying.
* Replace all `w_try cp` calls for `w_try_cp_dll` when they try to copy dlls into W_SYSTEM32_DLLS or W_SYSTEM64_DLLS.

wmp11 package:
* Remove dlls from both dll folders.
* Adding missing dlls.
Resident Evil on steam can now run. Tested with glorious eggroll proton.

There is probably a lot of other packages that will try to install stuff over symlinked dlls. That will cause one of 2 problems: Getting a permission denied if the target of the symlink is in a system folder without write access for the user. Or if the wine installation is writable by the user, its dlls will be overwritten, affecting all uses of that wine on all other prefixes, which is probably not what was intended.

2021-12-05 06:14 UTC, austin987 commented
```

+ grep -n -r [[:blank:]]$ src/winetricks
686:    
16656:    
src/winetricks contains trailing spaces, remove them. failed
```

Please fix that :)

2021-12-06 04:47 UTC, austin987 commented
It's still failing CI (now in shellcheck):
```

+ /usr/bin/shellcheck -s sh src/winetricks
======================== End shellcheck version info ===========================
Checking src/winetricks with shellcheck:

In src/winetricks line 685:
    [ -d "$2" ] && _W_destfile+="/$(basename "$1")"
                   ^---------^ SC2039: In POSIX sh, += is undefined.


In src/winetricks line 687:
    [ -h "$_W_destfile" ] && w_try rm -f "$_W_destfile"
          ^----------^ SC2250: Prefer putting braces around variable references even when not strictly required.
                                          ^----------^ SC2250: Prefer putting braces around variable references even when not strictly required.

Did you mean: 
    [ -h "${_W_destfile}" ] && w_try rm -f "${_W_destfile}"


In src/winetricks line 688:
    w_try cp -f "$1" "$_W_destfile"
                      ^----------^ SC2250: Prefer putting braces around variable references even when not strictly required.
```

To save time, try `./tests/shell-checks` locally before pushing :)

2021-12-06 05:05 UTC, patlefort commented
Ran it through shellcheck this time, should be all good. I get some other warnings but unrelated to my changes.

2021-12-06 05:24 UTC, austin987 requested changes
Thanks, took a closer look now that CI passes ;).

Aside from above comments, some git housekeeping requests: 70c8d519cee789d37e8a96e7491db82977a1362b "Add w_try_cp_dll function" should be renamed/split (adding the function and using it together are fine, but the wmp11 overrides belong in a separate commit (e.g., "wmp11: add native mfplat/wmasf overrides").

The other commits IMO could then be squashed into the first commit.

2021-12-06 05:24 UTC, austin987 commented on src/winetricks
> +    _W_destfile="$2"
Please give $1 a variable name and use it below as well (_W_srcfile/_W_srcdll).

2021-12-06 05:24 UTC, austin987 commented on src/winetricks
> +    [ -d "$2" ] && _W_destfile="${_W_destfile}/$(basename "$1")"
`$2` should be `_W_destfile` (and `$1` the new variable).

2021-12-06 05:24 UTC, austin987 commented on src/winetricks
> +    w_override_dlls native l3codeca.acm wmp wmplayer.exe wmvcore wmpnssci mfplat wmasf
Please keep these sorted.

2021-12-06 07:17 UTC, patlefort commented
Should be cleaned up.

2021-12-12 20:35 UTC, roman-bronis commented
It would be great if this got merged. It helped me to fix RE6 on Steam with latest Proton-GE (otherwise I was forced to use Proton 5.0). I believe this can help other games in the series as well.

2021-12-16 21:45 UTC, merged

2021-12-16 21:45 UTC, austin987 commented
Sorry for the delay; I wanted to make sure I ran the test suite before merging it ;).